version: '3.7'

services:
  db:
    image: mysql
    container_name: db_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'db_blog'
      # MYSQL_USER: 'springuser'
      # MYSQL_PASSWORD: 'C0kywtVj#'
    ports:
     - '3306:3306'

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '8085:8085'
    depends_on:
      - 'db'

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - 'backend'